spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 166900764134-vkmucqm5kgree44jueqpk29julkc06l3.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile